name: Despliegue Frontend to S3

on:
  push:
    branches:
      - main
      
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Revision de codigo
        uses: actions/checkout@v3

      - name: Identidad de AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-session-name: deploy_s3Github
          role-to-assume: ${{ secrets.AWS_AIM_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sincronizacion de archivos a S3
        run: |
          aws s3 sync ./ s3://${{ secrets.S3_BUCKET_NAME }} --delete
